export const drawFooter = (doc, settings) => {
  doc.moveDown(3);

  doc
    .moveTo(50, doc.y)
    .lineTo(545, doc.y)
    .stroke();

  doc.moveDown();

  doc
    .fontSize(10)
    .text(
      settings?.address ?? "",
      {
        align: "center",
      }
    );

  doc.text(
    settings?.phone ?? "",
    {
      align: "center",
    }
  );

  doc.text(
    settings?.email ?? "",
    {
      align: "center",
    }
  );

  doc.moveDown(2);

  doc.text(
    "Generated by YIZ-AMS",
    {
      align: "center",
    }
  );
};